"""Added Prompt dataclass to models

Revision ID: 7e0c11151f1b
Revises: 5c6cd274d34a
Create Date: 2023-04-02 02:52:31.103432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7e0c11151f1b'
down_revision = '5c6cd274d34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
